eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    preferIpAddress: ${DISCOVERY_PREFER_IP:true}
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 8
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URI:http://localhost:8761}/eureka/
    healthcheck:
      enabled: true

---

spring:
  profiles: cloudfoundry
eureka:
  instance:
    hostname: ${CF_INSTANCE_IP:${vcap.application.uris[0]}}
    nonSecurePort: ${CF_INSTANCE_PORT:${PORT:${server.port:80}}}
    preferIpAddress: false
  client:
    serviceUrl:
      defaultZone: ${vcap.services.discovery-service.credentials.url}/eureka/

---

spring:
  profiles: dev  
eureka:
    instance:
      leaseRenewalIntervalInSeconds: 5
    client:
      initialInstanceInfoReplicationIntervalSeconds: 5
      registryFetchIntervalSeconds: 2

