zuul:
  routes:
    frontend:
      path: /frontend/**
      serviceId: frontend-service
    identity:
      path: /identity/**
      serviceId: identity-service
      sensitiveHeaders:
    catalog:
      path: /catalog/**
      serviceId: catalogue-service-srdc
      sensitiveHeaders: Cookie,Set-Cookie
    business-process:
      path: /business-process/**
      serviceId: business-process-service
      sensitiveHeaders: Cookie,Set-Cookie
    data-channel:
      path: /data-channel/**
      serviceId: data-channel-service
      sensitiveHeaders: Cookie,Set-Cookie
    delegation:
      path: /delegation/**
      serviceId: delegate-service
      sensitiveHeaders: Cookie,Set-Cookie
    data-aggregation:
      path: /data-aggregation/**
      serviceId: data-aggregation-service
      sensitiveHeaders: Cookie,Set-Cookie
    search:
      path: /search/**
      serviceId: catalog-search-service
      sensitiveHeaders: Cookie,Set-Cookie
    tracking-analysis-service:
      path: /tnt/**
      serviceId: tracking-analysis-service
      sensitiveHeaders: Cookie,Set-Cookie
    tracking-service:
      path: /tracking/**
      serviceId: tracking-service
      sensitiveHeaders: Cookie,Set-Cookie
    trust:
      path: /trust/**
      serviceId: trust-service
      sensitiveHeaders: Cookie,Set-Cookie 
    index:
      path: /index/**
      serviceId: indexing-service
      sensitiveHeaders:
    frontend-fmp:
      path: /fmp/frontend/**
      serviceId: frontend-service-fmp
    frontend-efactory:
      path: /efpf/frontend/**
      serviceId: frontend-service-efactory
    frontend-efactory-efs:
      path: /efs/frontend/**
      serviceId: frontend-service-efs
    indexing-service-efs:
      path: /efsindex/**
      serviceId: indexing-service-efs
      sensitiveHeaders:
    identity-v2:
      path: /identity-v2/**
      serviceId: identity-service-v2
      sensitiveHeaders:
    semantic-lookup-service:
      path: /eclass/**
      serviceId: semantic-lookup-service
      sensitiveHeaders: Cookie,Set-Cookie
    registry-service:
      path: /registry-service/**
      serviceId: registry-service
      sensitiveHeaders: Cookie,Set-Cookie
    agents:
      path: /agents/**
      serviceId: agent-service
      sensitiveHeaders: Cookie,Set-Cookie
    asset-indexing:
      path: /assetindex/**
      serviceId: asset-indexing-service
      sensitiveHeaders: Cookie,Set-Cookie
    epcis-service:
      path: /epcis-server/**
      serviceId: epcis-service
      sensitiveHeaders: Cookie,Set-Cookie
    distributionnetwork:
      path: /distributionnetwork/**
      serviceId: distribution-network
      sensitiveHeaders: Cookie,Set-Cookie


spring:
  http:
    multipart:
     max-file-size: 1000MB
     max-request-size: 1000MB


---

spring:
  profiles: dev

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 8
  client:
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 2

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 500000

zuul:
  eureka:
    identity-service:
      semaphore:
        maxSemaphores: 300
    catalogue-service-srdc:
      semaphore:
        maxSemaphores: 300
    business-process-service:
      semaphore:
        maxSemaphores: 300
  host:
    connect-timeout-millis: 1000000
    socket-timeout-millis: 1000000
ribbon:
  ReadTimeout: 1000000
  ConnectTimeout: 1000000
